global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: grafana
    static_configs:
      - targets: [ 'localhost:3000' ]

  - job_name: node_exporter
    static_configs:
      - targets: [ 'localhost:9100' ]

  - job_name: postgres_exporter
    static_configs:
      - targets: [ 'localhost:9187' ]

  - job_name: redis_exporter
    static_configs:
      - targets: [ 'localhost:9121' ]

  - job_name: rabbitmq
    static_configs:
      - targets: [ 'localhost:15692' ]

  - job_name: wyvor_api
    static_configs:
      - targets: [ 'localhost:8001' ]

  - job_name: wyvor_bot
    static_configs:
      - targets: [ 'localhost:8002' ]

  - job_name: andesite
    static_configs:
      - targets: [ 'localhost:8004' ]

  - job_name: twilight_dispatch
    static_configs:
      - targets: [ 'localhost:8005' ]
