// Generated by events_gen.go

package events

import (
	"github.com/jonas747/discordgo"
)

const (
	EventAll                      = "all"
	EventChannelCreate            = "channel_create"
	EventChannelDelete            = "channel_delete"
	EventChannelPinsUpdate        = "channel_pins_update"
	EventChannelUpdate            = "channel_update"
	EventConnect                  = "connect"
	EventDisconnect               = "disconnect"
	EventGuildBanAdd              = "guild_ban_add"
	EventGuildBanRemove           = "guild_ban_remove"
	EventGuildCreate              = "guild_create"
	EventGuildDelete              = "guild_delete"
	EventGuildEmojisUpdate        = "guild_emojis_update"
	EventGuildIntegrationsUpdate  = "guild_integrations_update"
	EventGuildMemberAdd           = "guild_member_add"
	EventGuildMemberRemove        = "guild_member_remove"
	EventGuildMemberUpdate        = "guild_member_update"
	EventGuildMembersChunk        = "guild_members_chunk"
	EventGuildRoleCreate          = "guild_role_create"
	EventGuildRoleDelete          = "guild_role_delete"
	EventGuildRoleUpdate          = "guild_role_update"
	EventGuildUpdate              = "guild_update"
	EventInviteCreate             = "invite_create"
	EventInviteDelete             = "invite_delete"
	EventMessageAck               = "message_ack"
	EventMessageCreate            = "message_create"
	EventMessageDelete            = "message_delete"
	EventMessageDeleteBulk        = "message_delete_bulk"
	EventMessageReactionAdd       = "message_reaction_add"
	EventMessageReactionRemove    = "message_reaction_remove"
	EventMessageReactionRemoveAll = "message_reaction_remove_all"
	EventMessageUpdate            = "message_update"
	EventPresenceUpdate           = "presence_update"
	EventPresencesReplace         = "presences_replace"
	EventRateLimit                = "rate_limit"
	EventReady                    = "ready"
	EventRelationshipAdd          = "relationship_add"
	EventRelationshipRemove       = "relationship_remove"
	EventResumed                  = "resumed"
	EventTypingStart              = "typing_start"
	EventUserGuildSettingsUpdate  = "user_guild_settings_update"
	EventUserNoteUpdate           = "user_note_update"
	EventUserSettingsUpdate       = "user_settings_update"
	EventUserUpdate               = "user_update"
	EventVoiceServerUpdate        = "voice_server_update"
	EventVoiceStateUpdate         = "voice_state_update"
	EventWebhooksUpdate           = "webhooks_update"
)

var AllEvents = []string{
	EventChannelCreate,
	EventChannelDelete,
	EventChannelPinsUpdate,
	EventChannelUpdate,
	EventConnect,
	EventDisconnect,
	EventGuildBanAdd,
	EventGuildBanRemove,
	EventGuildCreate,
	EventGuildDelete,
	EventGuildEmojisUpdate,
	EventGuildIntegrationsUpdate,
	EventGuildMemberAdd,
	EventGuildMemberRemove,
	EventGuildMemberUpdate,
	EventGuildMembersChunk,
	EventGuildRoleCreate,
	EventGuildRoleDelete,
	EventGuildRoleUpdate,
	EventGuildUpdate,
	EventInviteCreate,
	EventInviteDelete,
	EventMessageAck,
	EventMessageCreate,
	EventMessageDelete,
	EventMessageDeleteBulk,
	EventMessageReactionAdd,
	EventMessageReactionRemove,
	EventMessageReactionRemoveAll,
	EventMessageUpdate,
	EventPresenceUpdate,
	EventPresencesReplace,
	EventRateLimit,
	EventReady,
	EventRelationshipAdd,
	EventRelationshipRemove,
	EventResumed,
	EventTypingStart,
	EventUserGuildSettingsUpdate,
	EventUserNoteUpdate,
	EventUserSettingsUpdate,
	EventUserUpdate,
	EventVoiceServerUpdate,
	EventVoiceStateUpdate,
	EventWebhooksUpdate,
}

var NewEvents = map[string]func() interface{}{
	"channel_create": func() interface{} {
		return &discordgo.ChannelCreate{}
	},
	"channel_delete": func() interface{} {
		return &discordgo.ChannelDelete{}
	},
	"channel_pins_update": func() interface{} {
		return &discordgo.ChannelPinsUpdate{}
	},
	"channel_update": func() interface{} {
		return &discordgo.ChannelUpdate{}
	},
	"connect": func() interface{} {
		return &discordgo.Connect{}
	},
	"disconnect": func() interface{} {
		return &discordgo.Disconnect{}
	},
	"guild_ban_add": func() interface{} {
		return &discordgo.GuildBanAdd{}
	},
	"guild_ban_remove": func() interface{} {
		return &discordgo.GuildBanRemove{}
	},
	"guild_create": func() interface{} {
		return &discordgo.GuildCreate{}
	},
	"guild_delete": func() interface{} {
		return &discordgo.GuildDelete{}
	},
	"guild_emojis_update": func() interface{} {
		return &discordgo.GuildEmojisUpdate{}
	},
	"guild_integrations_update": func() interface{} {
		return &discordgo.GuildIntegrationsUpdate{}
	},
	"guild_member_add": func() interface{} {
		return &discordgo.GuildMemberAdd{}
	},
	"guild_member_remove": func() interface{} {
		return &discordgo.GuildMemberRemove{}
	},
	"guild_member_update": func() interface{} {
		return &discordgo.GuildMemberUpdate{}
	},
	"guild_members_chunk": func() interface{} {
		return &discordgo.GuildMembersChunk{}
	},
	"guild_role_create": func() interface{} {
		return &discordgo.GuildRoleCreate{}
	},
	"guild_role_delete": func() interface{} {
		return &discordgo.GuildRoleDelete{}
	},
	"guild_role_update": func() interface{} {
		return &discordgo.GuildRoleUpdate{}
	},
	"guild_update": func() interface{} {
		return &discordgo.GuildUpdate{}
	},
	"invite_create": func() interface{} {
		return &discordgo.InviteCreate{}
	},
	"invite_delete": func() interface{} {
		return &discordgo.InviteDelete{}
	},
	"message_ack": func() interface{} {
		return &discordgo.MessageAck{}
	},
	"message_create": func() interface{} {
		return &discordgo.MessageCreate{}
	},
	"message_delete": func() interface{} {
		return &discordgo.MessageDelete{}
	},
	"message_delete_bulk": func() interface{} {
		return &discordgo.MessageDeleteBulk{}
	},
	"message_reaction_add": func() interface{} {
		return &discordgo.MessageReactionAdd{}
	},
	"message_reaction_remove": func() interface{} {
		return &discordgo.MessageReactionRemove{}
	},
	"message_reaction_remove_all": func() interface{} {
		return &discordgo.MessageReactionRemoveAll{}
	},
	"message_update": func() interface{} {
		return &discordgo.MessageUpdate{}
	},
	"presence_update": func() interface{} {
		return &discordgo.PresenceUpdate{}
	},
	"presences_replace": func() interface{} {
		return &discordgo.PresencesReplace{}
	},
	"rate_limit": func() interface{} {
		return &discordgo.RateLimit{}
	},
	"ready": func() interface{} {
		return &discordgo.Ready{}
	},
	"relationship_add": func() interface{} {
		return &discordgo.RelationshipAdd{}
	},
	"relationship_remove": func() interface{} {
		return &discordgo.RelationshipRemove{}
	},
	"resumed": func() interface{} {
		return &discordgo.Resumed{}
	},
	"typing_start": func() interface{} {
		return &discordgo.TypingStart{}
	},
	"user_guild_settings_update": func() interface{} {
		return &discordgo.UserGuildSettingsUpdate{}
	},
	"user_note_update": func() interface{} {
		return &discordgo.UserNoteUpdate{}
	},
	"user_settings_update": func() interface{} {
		return &discordgo.UserSettingsUpdate{}
	},
	"user_update": func() interface{} {
		return &discordgo.UserUpdate{}
	},
	"voice_server_update": func() interface{} {
		return &discordgo.VoiceServerUpdate{}
	},
	"voice_state_update": func() interface{} {
		return &discordgo.VoiceStateUpdate{}
	},
	"webhooks_update": func() interface{} {
		return &discordgo.WebhooksUpdate{}
	},
}

func (event *EventData) ChannelCreate() *discordgo.ChannelCreate {
	return event.Event.(*discordgo.ChannelCreate)
}

func (event *EventData) ChannelDelete() *discordgo.ChannelDelete {
	return event.Event.(*discordgo.ChannelDelete)
}

func (event *EventData) ChannelPinsUpdate() *discordgo.ChannelPinsUpdate {
	return event.Event.(*discordgo.ChannelPinsUpdate)
}

func (event *EventData) ChannelUpdate() *discordgo.ChannelUpdate {
	return event.Event.(*discordgo.ChannelUpdate)
}

func (event *EventData) Connect() *discordgo.Connect {
	return event.Event.(*discordgo.Connect)
}

func (event *EventData) Disconnect() *discordgo.Disconnect {
	return event.Event.(*discordgo.Disconnect)
}

func (event *EventData) GuildBanAdd() *discordgo.GuildBanAdd {
	return event.Event.(*discordgo.GuildBanAdd)
}

func (event *EventData) GuildBanRemove() *discordgo.GuildBanRemove {
	return event.Event.(*discordgo.GuildBanRemove)
}

func (event *EventData) GuildCreate() *discordgo.GuildCreate {
	return event.Event.(*discordgo.GuildCreate)
}

func (event *EventData) GuildDelete() *discordgo.GuildDelete {
	return event.Event.(*discordgo.GuildDelete)
}

func (event *EventData) GuildEmojisUpdate() *discordgo.GuildEmojisUpdate {
	return event.Event.(*discordgo.GuildEmojisUpdate)
}

func (event *EventData) GuildIntegrationsUpdate() *discordgo.GuildIntegrationsUpdate {
	return event.Event.(*discordgo.GuildIntegrationsUpdate)
}

func (event *EventData) GuildMemberAdd() *discordgo.GuildMemberAdd {
	return event.Event.(*discordgo.GuildMemberAdd)
}

func (event *EventData) GuildMemberRemove() *discordgo.GuildMemberRemove {
	return event.Event.(*discordgo.GuildMemberRemove)
}

func (event *EventData) GuildMemberUpdate() *discordgo.GuildMemberUpdate {
	return event.Event.(*discordgo.GuildMemberUpdate)
}

func (event *EventData) GuildMembersChunk() *discordgo.GuildMembersChunk {
	return event.Event.(*discordgo.GuildMembersChunk)
}

func (event *EventData) GuildRoleCreate() *discordgo.GuildRoleCreate {
	return event.Event.(*discordgo.GuildRoleCreate)
}

func (event *EventData) GuildRoleDelete() *discordgo.GuildRoleDelete {
	return event.Event.(*discordgo.GuildRoleDelete)
}

func (event *EventData) GuildRoleUpdate() *discordgo.GuildRoleUpdate {
	return event.Event.(*discordgo.GuildRoleUpdate)
}

func (event *EventData) GuildUpdate() *discordgo.GuildUpdate {
	return event.Event.(*discordgo.GuildUpdate)
}

func (event *EventData) InviteCreate() *discordgo.InviteCreate {
	return event.Event.(*discordgo.InviteCreate)
}

func (event *EventData) InviteDelete() *discordgo.InviteDelete {
	return event.Event.(*discordgo.InviteDelete)
}

func (event *EventData) MessageAck() *discordgo.MessageAck {
	return event.Event.(*discordgo.MessageAck)
}

func (event *EventData) MessageCreate() *discordgo.MessageCreate {
	return event.Event.(*discordgo.MessageCreate)
}

func (event *EventData) MessageDelete() *discordgo.MessageDelete {
	return event.Event.(*discordgo.MessageDelete)
}

func (event *EventData) MessageDeleteBulk() *discordgo.MessageDeleteBulk {
	return event.Event.(*discordgo.MessageDeleteBulk)
}

func (event *EventData) MessageReactionAdd() *discordgo.MessageReactionAdd {
	return event.Event.(*discordgo.MessageReactionAdd)
}

func (event *EventData) MessageReactionRemove() *discordgo.MessageReactionRemove {
	return event.Event.(*discordgo.MessageReactionRemove)
}

func (event *EventData) MessageReactionRemoveAll() *discordgo.MessageReactionRemoveAll {
	return event.Event.(*discordgo.MessageReactionRemoveAll)
}

func (event *EventData) MessageUpdate() *discordgo.MessageUpdate {
	return event.Event.(*discordgo.MessageUpdate)
}

func (event *EventData) PresenceUpdate() *discordgo.PresenceUpdate {
	return event.Event.(*discordgo.PresenceUpdate)
}

func (event *EventData) PresencesReplace() *discordgo.PresencesReplace {
	return event.Event.(*discordgo.PresencesReplace)
}

func (event *EventData) RateLimit() *discordgo.RateLimit {
	return event.Event.(*discordgo.RateLimit)
}

func (event *EventData) Ready() *discordgo.Ready {
	return event.Event.(*discordgo.Ready)
}

func (event *EventData) RelationshipAdd() *discordgo.RelationshipAdd {
	return event.Event.(*discordgo.RelationshipAdd)
}

func (event *EventData) RelationshipRemove() *discordgo.RelationshipRemove {
	return event.Event.(*discordgo.RelationshipRemove)
}

func (event *EventData) Resumed() *discordgo.Resumed {
	return event.Event.(*discordgo.Resumed)
}

func (event *EventData) TypingStart() *discordgo.TypingStart {
	return event.Event.(*discordgo.TypingStart)
}

func (event *EventData) UserGuildSettingsUpdate() *discordgo.UserGuildSettingsUpdate {
	return event.Event.(*discordgo.UserGuildSettingsUpdate)
}

func (event *EventData) UserNoteUpdate() *discordgo.UserNoteUpdate {
	return event.Event.(*discordgo.UserNoteUpdate)
}

func (event *EventData) UserSettingsUpdate() *discordgo.UserSettingsUpdate {
	return event.Event.(*discordgo.UserSettingsUpdate)
}

func (event *EventData) UserUpdate() *discordgo.UserUpdate {
	return event.Event.(*discordgo.UserUpdate)
}

func (event *EventData) VoiceServerUpdate() *discordgo.VoiceServerUpdate {
	return event.Event.(*discordgo.VoiceServerUpdate)
}

func (event *EventData) VoiceStateUpdate() *discordgo.VoiceStateUpdate {
	return event.Event.(*discordgo.VoiceStateUpdate)
}

func (event *EventData) WebhooksUpdate() *discordgo.WebhooksUpdate {
	return event.Event.(*discordgo.WebhooksUpdate)
}
